# Generated by Django 5.0.1 on 2024-01-28 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(blank=True, choices=[('-debit', '-debit'), ('+credit', '+credit')], default=' ', max_length=20, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceCreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('bkash', 'bkash'), ('nogod', 'nogod'), ('rokect', 'rokect'), ('upay', 'upay')], default=' ', max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('trxid', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_amounts', models.CharField(blank=True, max_length=20, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('balance_history', models.ManyToManyField(blank=True, to='payments.balancehistory')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('method', models.CharField(blank=True, choices=[('bkash', 'bkash'), ('nogod', 'nogod'), ('rokect', 'rokect'), ('upay', 'upay')], default=' ', max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
