# Generated by Django 5.0.3 on 2024-04-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceCreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, choices=[('bkash', 'bkash'), ('nogod', 'nogod'), ('rokect', 'rokect'), ('upay', 'upay')], default=' ', max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('trxid', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_amounts', models.CharField(blank=True, max_length=20, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(blank=True, choices=[('-debit', '-debit'), ('+credit', '+credit')], default=' ', max_length=20, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('withdraw_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('method', models.CharField(blank=True, choices=[('bkash', 'bkash'), ('nogod', 'nogod'), ('rokect', 'rokect'), ('upay', 'upay')], default=' ', max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('price_bn', models.CharField(blank=True, max_length=20, null=True)),
                ('access_time', models.CharField(blank=True, max_length=20, null=True)),
                ('access_time_bn', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('main_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_history', models.ManyToManyField(blank=True, to='payments.balancehistory')),
            ],
        ),
    ]
