# Generated by Django 5.0.1 on 2024-01-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(blank=True, choices=[('-debit', '-debit'), ('+credit', '+credit')], default=' ', max_length=20, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_history', models.ManyToManyField(to='payments.balance_history')),
            ],
        ),
    ]
