# Generated by Django 5.0.1 on 2024-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_balance_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='access_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='access_time_bn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name_bn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_bn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
