# Generated by Django 5.0.3 on 2024-03-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscription_access_time_subscription_access_time_bn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='balancecreditrequest',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='balancewithdrawrequest',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
