# Generated by Django 5.0.1 on 2024-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=20, null=True)),
                ('title2', models.CharField(blank=True, max_length=20, null=True)),
                ('title3', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('book_image_1', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('book_image_2', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('book_image_3', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('book_image_4', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('book_banar1', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('book_banar2', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/about/')),
            ],
        ),
        migrations.CreateModel(
            name='LandingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('offer_box', models.ManyToManyField(blank=True, to='payments.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('image_banar', models.ImageField(blank=True, null=True, upload_to='landing/about/')),
                ('title2', models.CharField(blank=True, max_length=100, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('team_section', models.ManyToManyField(blank=True, to='landing.teamprofile')),
            ],
        ),
    ]
