# Generated by Django 5.0.1 on 2024-01-27 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('titleBn', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('detailsBn', models.TextField(blank=True, null=True)),
                ('categories_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('categories_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Free_book_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('book_page_number', models.CharField(blank=True, max_length=100, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='free_pages/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(blank=True, max_length=50, null=True)),
                ('book_title_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('book_details', models.TextField(blank=True, null=True)),
                ('book_details_bn', models.TextField(blank=True, null=True)),
                ('book_subject_code', models.CharField(blank=True, max_length=10, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('book_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.session')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter_number', models.CharField(blank=True, max_length=20, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Free_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('book_images', models.ManyToManyField(to='books.free_book_page')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='free_book_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.free_books'),
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pages_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pages_images', models.ImageField(blank=True, null=True, upload_to='book_pages/')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.chapter')),
            ],
        ),
    ]
