# Generated by Django 5.0.1 on 2024-01-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('titleBn', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.CharField(blank=True, max_length=30, null=True)),
                ('detailsBn', models.CharField(blank=True, max_length=30, null=True)),
                ('categories_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('categories_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
