# Generated by Django 5.0.1 on 2024-01-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='detailsBn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
