# Generated by Django 5.0.1 on 2024-01-30 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.categories'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.session'),
        ),
        migrations.AlterField(
            model_name='book',
            name='free_book_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.freebooks'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='chapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.chapter'),
        ),
    ]
