# Generated by Django 5.0.1 on 2024-01-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_categories_details_alter_categories_detailsbn'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(blank=True, max_length=30, null=True)),
                ('book_title_bn', models.CharField(blank=True, max_length=30, null=True)),
                ('book_details', models.TextField(blank=True, null=True)),
                ('book_details_bn', models.TextField(blank=True, null=True)),
                ('book_subject_code', models.CharField(blank=True, max_length=10, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('book_free_pdf', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('book_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.session')),
            ],
        ),
    ]
