# Generated by Django 5.0.3 on 2024-04-02 18:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReadedChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2024, 4, 2, 11, 12, 40, 256062), null=True)),
                ('book_readed_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitedChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2024, 4, 2, 11, 12, 40, 256062), null=True)),
                ('site_visited_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('access_book', models.ManyToManyField(blank=True, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReadedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('readed_book', models.ManyToManyField(blank=True, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='UserBookReadedChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('datas', models.ManyToManyField(blank=True, to='accounts.bookreadedchartdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], default=' ', max_length=20, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.balance')),
            ],
        ),
        migrations.CreateModel(
            name='UserSiteVisitedChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('datas', models.ManyToManyField(blank=True, to='accounts.sitevisitedchartdata')),
            ],
        ),
    ]
