# Generated by Django 5.0.1 on 2024-01-29 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bookreadedchartdata_date_and_more'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessbook',
            name='access_book',
        ),
        migrations.AlterField(
            model_name='bookreadedchartdata',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 29, 15, 29, 27, 27189), null=True),
        ),
        migrations.AlterField(
            model_name='sitevisitedchartdata',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 29, 15, 29, 27, 28184), null=True),
        ),
        migrations.AddField(
            model_name='accessbook',
            name='access_book',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
