# Generated by Django 5.0.3 on 2024-03-26 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_bookreadedchartdata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessbook',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookreadedchartdata',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 27, 3, 42, 41, 466745), null=True),
        ),
        migrations.AlterField(
            model_name='readedbook',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisitedchartdata',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 27, 3, 42, 41, 466745), null=True),
        ),
        migrations.AlterField(
            model_name='userbookreadedchart',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersitevisitedchart',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
