# Generated by Django 5.0.3 on 2024-03-26 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_accessbook_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreadedchartdata',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 27, 3, 43, 19, 715736), null=True),
        ),
        migrations.AlterField(
            model_name='sitevisitedchartdata',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 27, 3, 43, 19, 715736), null=True),
        ),
    ]
